RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
VIA_ENABLE      = no
OLED_ENABLE     = yes
COMBO_ENABLE    = yes
LTO_ENABLE      = yes
WPM_ENABLE      = yes
CONSOLE_ENABLE  = no

# Smaller filesize
LINK_TIME_OPTIMIZATION_ENABLE = yes

TAP_DANCE_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no
ENCODER_ENABLE = no
